### ISSUE TITLE
I can't get my Hit and Stay buttons to work.

### ISSUE THREAD

**Issue by ashleybaird** [ashleybaird/ashleybaird.github.io#2]
When the user clicks newGame the game resets and allows the user to play again. Though if the user tries to hit newGame again the Hit and Stay buttons are off. In the newGame function I declared for it to turn back on the click, but I have no idea why it only works one time. 

```
$('#newGame').click(function(){
    $('div').remove();
    $userTotal;
    $dealerTotal;
    $dealerHand = [];
    $userHand = [];
     move();

    $('#Hit').on('click');
    $('#Stay').on('click');

})

```

**Comment by andrewfritz86** [comment]
OK. Are you passing any callbacks to the #hit and #stay buttons? Looks like you are only passing them "click"

**Comment by ashleybaird** [comment]
I wasn't. Thanks for the help! Such a silly mistake haha

**Comment by andrewfritz86** [comment]
Yay!
